name: InteliJ Compatibility Verification

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Verify Plugin Compatibility
      run: gradle compatibilityCheck
